[package]
name = "xlz"
authors = ["JacobX <jacobbishopxy@gmail.com>"]
version = "0.1.0"
edition = "2018"

[dependencies]
calamine = "0.18.0"
derivative = "2.2.0"
failure = "0.1.8"
linked-hash-map = "0.5.4"
quick-xml = { version = "0.22.0", features = ["serialize"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "1.0.26"
zip = "0.5.13"
