[package]
name = "xlz"
authors = ["JacobX <jacobbishopxy@gmail.com>"]
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.42"
chrono = "0.4.19"
derivative = "2.2.0"
quick-xml = { version = "0.22.0", features = ["serialize"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
zip = "0.5.13"
