[package]
name = "xlz"
authors = ["JacobX <jacobbishopxy@gmail.com>"]
version = "0.1.0"
edition = "2018"

[dependencies]
calamine = "0.18.0"
failure = "0.1.8"
itertools = "0.10.1"
ooxml = "0.2.4"
quick-xml = "0.22.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
