[package]
name = "uv-backend"
authors = ["JacobX <jacobbishopxy@gmail.com>"]
version = "0.1.0"
edition = "2018"

[dependencies]
actix-cors = "0.5.4"
actix-web = "3.3.2"
env_logger = "0.8.4"
futures = "0.3.15"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
